### ISSUE TITLE
Flexible layouts in ACFE modal are not filtered when they have no category set

### ISSUE THREAD

**Issue by ghost** [acf-extended/ACF-Extended#102]
It select only layouts which have a data-attribute `acfe-flexible-category` but as you can see in this screenshot, by default ACFE doesn't add this attribute when no category is set.

![image](https://user-images.githubusercontent.com/62112531/178010282-ec6288e5-45dd-47b3-869b-a1ddd8289b55.png)

It's because of this line:   
https://github.com/acf-extended/ACF-Extended/blob/ecc5cef89aa3a5ebb8079eceb04f985f8b09d937/assets/js/acfe-input.js#L1705

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback!

Yes, this will be fixed in teh next patch.

Sorry for the inconvenience.

Have a nice day!

Regards.

**Comment by acf-extended** [comment]
Hello,

This has been fixed in the latest 0.8.8.8 release.

Have a nice day!

Regards.
