### ISSUE TITLE
Will the updated ACF UI cause issues for ACF Extended

### ISSUE THREAD

**Issue by impartdan** [acf-extended/ACF-Extended#105]
ACF recently announced a new UI that the have a release candidate for, see here: [https://www.advancedcustomfields.com/blog/acf-pro-6-0-rc-1/](https://www.advancedcustomfields.com/blog/acf-pro-6-0-rc-1/)

Will this cause issues for ACF Extended? Has anyone kicked the tires on this RC?

**Comment by acf-extended** [comment]
Hello,

I'm working with the ACF team since the RC to make the transition smoothly. The first patch came out few hours after the ACF 6.0 official release. More patch will come as ACF team keep fixing stuff on their end too.

Hope it answers your question!

Have a nice day!

Regards.
