### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by maximejobin** [acf-extended/ACF-Extended#106]
We just bought a PRO license. There was a great roadmap and new versions released every month at the beginning of 2021.

Nothing happened in 2022.

The question is : is this project dead?

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback!

ACF Extended is still very much maintained, please see the related answer below. For further assistance with your Pro license, please use the ticket system from your account, as it's easier for me to centralize everything at the same place :)

> Yes it is. It’s the holiday season, so I’m taking some fresh air in order to come back stronger.

> The upcoming update is a pretty big one, which rework and improve a lot of important parts of the code. So I want to fully test it and make it fully compatible with older version before releasing it. I prefer a delayed release than a rushed release with potential bugs.

> The current version is pretty stable, as there is no breaking bug or error. Indeed, I keep an eye on this support forum since I receive all notification by email (as you can see I answered you within 10 minutes). But questions asked here so far are more related to custom ACF development rather than actual bug report. Since I want to deliver high quality answers to everyone, I have to give higher priority to questions asked by pro users at the moment.

> The situation should come back to the normal later this summer.

> Hope it answer your questions.

Have a nice day!

Regards.

**Comment by maximejobin** [comment]
Thank you for taking the time, Konrad. I'm happy to know it's not dead.

Welcome back!! :-)
