### ISSUE TITLE
php sync for "block types"

### ISSUE THREAD

**Issue by yangkennyk** [acf-extended/ACF-Extended#11]
**Is your feature request related to a problem? Please describe.**
PHP sync for "block types" so that it's not relying on the database.

**Describe the solution you'd like**
A php sync file is generated for created "block types" just like field group php sync.

**Describe alternatives you've considered**
Manually exporting the blocks with the php export feature.

**Additional context**
Currently working on a multisite instance that utilizes acfe php sync for field groups. Started to use the "block types" feature but realized it's not php synced so the "block types" do not show up on the sub sites.

**Comment by acf-extended** [comment]
Hello,

The latest ACF Extended 0.8.3.1 version added manually PHP export for ACF Block Types. The PHP AutoSync is an another story, I need to think about a global solution for all modules (Dynamic Post Types/Taxonomies/Options Pages etc...).

Regards.

**Comment by acf-extended** [comment]
Hello,

I'm closing this ticket since the feature request has been added to the Trello Board: https://www.acf-extended.com/roadmap

Have a nice day!

Regards.
