### ISSUE TITLE
Dynamic Preview not working

### ISSUE THREAD

**Issue by bobhuf** [acf-extended/ACF-Extended#110]
Hello,

I'm unable to get Dynamic Preview (layout preview in the administration) working. has_flexible and get_flexible are functioning just fine in my templates (Timber/twig) so I assume the field is set up correctly. Is there anything I can do to debug this?

I'm using this technique for the templates: https://github.com/acf-extended/ACF-Extended/issues/26#issuecomment-625178802
The field group's json: https://www.dropbox.com/s/od35yx8x6yfd5nu/acf-export-2022-12-30.json

**WordPress & ACF**
WordPress version: 6.1.1
ACF Pro version: 6.0.6
ACF extended: 0.8.8.11
(clean wp install, no other plugins installed)

Theme: [Timber starter theme](https://github.com/timber/starter-theme)

Thank you.

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback!

Unfortunately I don't use Timber/Twig, so I can't really give you any insight here. What I can confirm you is that the classic PHP version works.

I would recommend to check the Timber/Twig developer community see if they have some additional debugging tools. Or maybe contacting the developer from #26 for more information.

Hope it helps!

Have a nice day!

Regards.
