### ISSUE TITLE
Please keep supporting classic versions of WordPress

### ISSUE THREAD

**Issue by ghost** [acf-extended/ACF-Extended#111]
Currently working on a non-blocky version of WordPress ([wp-cms](https://github.com/wp-cms/wp-cms)), which doesn't contain block-related functions. There also is ClassicPress.

This issue is just to gently ask for your support by conditionally checking if the plugin is running on a "blocky" version of WP when using blocky stuff.

That way the plugin will keep working fine on WP-CMS and ClassicPress.

This is a fundamental plugin for the WP ecosystem, please don't leave non-blocky people behind.

Thanks.

**Comment by castellanario** [comment]
+1

**Comment by salamarkesa** [comment]
Yes, please! :)

**Comment by harmony-developer** [comment]
Exactly, hope it keeps working because I will never use the blocks version of WordPress.
