### ISSUE TITLE
Global conditional field doesn't work

### ISSUE THREAD

**Issue by thorin31** [acf-extended/ACF-Extended#117]
When I setup a field as global conditional logic, I found it in all my other group fields field. But If I use it, the field I setup with this global doesn't display.

On a page option, I added a radio field with 2 options. I put 1 & 2 as values for 2 radios. I set up as global conditional logic.
On another group field, I ask to display this field only if the value of my global field is equal 2.
I tried a lot of kind of values but the field never shows up...

**WordPress & ACF**
WordPress version: 6.2.2
ACF Pro version: 6.1.6
ACF add-ons: 0.8.9.3

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback!

The Global Conditional Logic is a ACF Extended Pro feature. Unfortunately, I cannot provide support for pro users on this forum.

Please open a ticket from your [Account Dashboard](https://www.acf-extended.com/account) instead.

Thanks!

Have a nice day!

Regards.

**Comment by thorin31** [comment]
ok, thank you.
