### ISSUE TITLE
Pre-existing field group missing fields with ACFE enabled

### ISSUE THREAD

**Issue by MSERobert** [acf-extended/ACF-Extended#120]
**Describe the bug**
I was checking out your plugin and noticed that one of my pre-existing field groups was missing some of its fields and the "add field" button.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
I expected to see all the fields in my field group

**Screenshots**
With ACFE disabled:
![image](https://github.com/acf-extended/ACF-Extended/assets/63687283/1c599090-c12d-4416-aff4-34d9499b674a)

With ACFE enabled:
![image](https://github.com/acf-extended/ACF-Extended/assets/63687283/8ff5f050-a5d5-4617-9405-2e113c744187)

**WordPress & ACF**
WordPress version: 6.3.1
ACF Pro version: 6.2.1
ACF add-ons: I removed the few add-ons I use but it still fails..

**Comment by MSERobert** [comment]
With ACFE enabled I also get the following errors in the browser console:
![image](https://github.com/acf-extended/ACF-Extended/assets/63687283/f46bc5a9-6742-4212-bf88-8e49b11a1c5c)
![image](https://github.com/acf-extended/ACF-Extended/assets/63687283/c926d242-e45c-4207-b700-da1816a8d113)

**Comment by acf-extended** [comment]
Hello,

Answered the ticket on the [WP repository](https://wordpress.org/support/topic/pre-existing-field-group-missing-fields-with-acfe-enabled/).

Regards.
