### ISSUE TITLE
ACF Options Polylang extended support

### ISSUE THREAD

**Issue by wpsumo** [acf-extended/ACF-Extended#125]
**Is your feature request related to a problem? Please describe.**
Polylang doesn't support ACF options page by default. The third-party plugin that used to work is no longer actively maintained.

**Describe the solution you'd like**
At the core, the same functionality as ACF options for polling but improved and extended.

Right now values will be the same for all languages you have set. Be able to set a different value for each language, and if none is set, the “All languages” value will be used as default one.

How ?

This plugin will store a value for each language into database. Then Polylang’s languages are used to get the values from the DB. That means at activation, all existing data will not be anymore available, but still in database. You will retrieve it at plugin deactivation.

Then to set and contribute your option page, simply use the Polylang’s language admin flags ui.

**Describe alternatives you've considered**
Is there something ACF extended can do now when this plugin is not maintained anymore? https://wordpress.org/plugins/acf-options-for-polylang/

**Additional context**

**Comment by acf-extended** [comment]
Hello,

Yes, ACF Extended has a multilingual module that adds compatibility for Polylang on ACF Options Pages. [See documentation](https://www.acf-extended.com/features/wordpress/polylang).

When ACF Extended is activated, `get_field('my_field', 'options')` on front-end will use the values set as Default Language on the Options page.

If the user switch to another language on front-end, and there is no translation for the Options Page for the said language, it will display the default language too.

In the back-end, you can switch language on your ACF Options Page to be able to translate each field. These translated fields will then be used on the front-end when user switch language.

Hope it helps!

Have a nice day!

Regards.

**Comment by wpsumo** [comment]
Ok great! So https://wordpress.org/plugins/acf-options-for-polylang/ is obsolete?

**Comment by wpsumo** [comment]
@acf-extended Is that correct?

**Comment by acf-extended** [comment]
Hello,

I am not the author of the "ACF Options for Polylang" plugin.
Please open a ticket on their repository if you need further information.

Thanks!

Regards.
