### ISSUE TITLE
Add copy/paste strings to .po file

### ISSUE THREAD

**Issue by yehrhardt** [acf-extended/ACF-Extended#127]
It would be nice to have the copy/paste Texts in the .po translation file.

At the moment, they are hardcoded here for example: https://github.com/acf-extended/ACF-Extended/blob/6ad9de5ee5255149a95759cd792d63bde6b1571f/includes/fields/field-flexible-content-actions.php#L440

![image](https://github.com/acf-extended/ACF-Extended/assets/124149785/e147c360-48e0-4ede-a5b5-fc0919a0f098)

Which leads to a mix/match of german/english in my case (element-view):
![image](https://github.com/acf-extended/ACF-Extended/assets/124149785/6804f33a-8f3c-475b-b135-65bb2764436d)

JS Alert:
![image](https://github.com/acf-extended/ACF-Extended/assets/124149785/9be60442-b1d6-4a3b-b4de-3bc7869a4812)
(translated via the .po file to german)

Thank you!

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback!

Yes, this is an oversight. I'm adding it on my todo list for the next patch.

Thanks!

Regards.

**Comment by acf-extended** [comment]
Hello,

Just a heads up to let you know the latest ACF Extended 0.9.0.6 version added the missing localized strings in Flexible Content.

Have a nice day!

Regards.
