### ISSUE TITLE
Repeaters are forced to use stylized button when created with acf-builder

### ISSUE THREAD

**Issue by mindfullsilence** [acf-extended/ACF-Extended#128]
**Describe the bug**
Repeater fields show the "Stylized Button" described [here](https://www.acf-extended.com/features/fields/repeater) when created with [acf-builder](https://github.com/StoutLogic/acf-builder), regardless of setting true, false, or not setting at all. 

**To Reproduce**
Create a repeater via acf-builder programmatically:

```php
$builder = new FieldsBuilder('some-group');
$builder
  ->addRepeater('my_repeater');
  // ->setConfig('acfe_repeater_stylised_button', 0) has no effect

$builder->addLocation('post_type', '==', 'page');

acf_add_local_field_group($builder->build());
```

**Expected behavior**
Should be able to turn on/off this configuration per repeater field by setting its value to true or false. 

**WordPress & ACF**
WordPress version: 6.5.5
ACF Pro version: 6.3.3
ACF add-ons:
  - ACF Extended 0.6.0.9

**Related file (I think this is where the issue is):**
[field-repeater.php#L61-63](https://github.com/acf-extended/ACF-Extended/blob/master/includes/fields/field-repeater.php#L62)
```php
// Currently this
if(isset($field['acfe_repeater_stylised_button'])){
    $wrapper['data-acfe-repeater-stylised-button'] = 1;
}

// Should probably be this
if(isset($field['acfe_repeater_stylised_button'])){
    $wrapper['data-acfe-repeater-stylised-button'] = $field['acfe_repeater_stylised_button'];
}
```

**Current workaround I'm using in theme functions.php:**
```php
add_filter('acf/load_field/type=repeater', function($field) {
    unset($field['acfe_repeater_stylised_button']);

    return $field;
}, 10, 1);
```

**Comment by mindfullsilence** [comment]
Thanks! Excellent plugin, btw. My admin is just so dang clean now :D

**Comment by acf-extended** [comment]
Hello,

Just a heads up to let you I think there was a misunderstanding.

I checked the code, and it is actually correct. There is no reason the Stylised Button to show unless you specifically set `acfe_repeater_stylised_button = true`. It is `false` by default, so it won't show up.

The code is pretty straight forward:
```php
if($field['acfe_repeater_stylised_button']){
    $wrapper['data-acfe-repeater-stylised-button'] = 1;
}
```

Which means: if acfe_repeater_stylised_button is `true` or has any value other than `false`, then display the Sylised Button.

I'm not sure if the issue come from acf-builder (which might automatically set it to `true`), or if you have a custom code/hook somewhere which does that.

Regards.
