### ISSUE TITLE
"Advanced Link" fails required validation if post object is selected

### ISSUE THREAD

**Issue by yangkennyk** [acf-extended/ACF-Extended#13]
**Describe the bug**
The "Advanced Link" field type fails validation if it's set to required and you select a post instead of URL

**To Reproduce**
Create "Advanced Link" and make it required. Try to save the field and select a post instead of URL

**Expected behavior**
The validation should pass if a post is selected.

**WordPress & ACF**
WordPress version: 5.3.2
ACF Pro version: 5.8.7

**Comment by acf-extended** [comment]
Hello,

Thanks for the report, I added the bug to the Trello board: https://trello.com/b/QEgpU7CL/acf-extended

I'll investigate the problem and try to fix it for the next patch!

Regards.

**Comment by acf-extended** [comment]
Hello,

Just to let you know that the latest 0.8.4 update include this fix 🙂

Regards.
