### ISSUE TITLE
fatal error module-performance-ultra

### ISSUE THREAD

**Issue by bobhuf** [acf-extended/ACF-Extended#131]
I used the official WP importer to move a set of custom posts to a staging server. Whenever these posts are edited, a fatal error occurs:

> Fatal error: Uncaught Error: Cannot access offset of type string on string in /wp-content/plugins/acf-extended/includes/modules/performance/module-performance-ultra.php

The field setup can be seen here: https://pastebin.com/Yv0g4Rau
Performance mode is enabled in my theme with acf_update_setting('acfe/modules/performance', true);
Newly created posts are unaffected.

Plot twist: a second CPT, imported at the same time, is unaffected. Both CPT’s are created using ACF.

Not sure where to begin on this one. Tried setting the affected CPT fields to ‘save as individual meta’ but that didn’t work.

ps: I also posted this to the WP support forums, apologies...

**Comment by bobhuf** [comment]
Follow up question: will the [Hybrid Engine](https://www.acf-extended.com/features/modules/performance-mode/hybrid-engine) solve this issue?

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback!

I answered you there: https://wordpress.org/support/topic/fatal-error-module-performance-ultra-php/

Let's continue the discussion on the WP support thread, to avoid spreading out and losing information. 

Thanks!

Regards.
