### ISSUE TITLE
Uploaded images are not attached to post in the Gallery field in a front-end form

### ISSUE THREAD

**Issue by VladNov** [acf-extended/ACF-Extended#133]
**Describe the bug**
The Gallery field is set to the "Uploaded to post" option with WP uploader and used in a front-end form in CPT. The Media window does not show the images which were just uploaded (screenshot 1) and the Media library page inside the admin, show the images as "(Unattached)" (screenshot 2). Tested with acf_form() and acfe_form().

**To Reproduce**
1. Add Gallery field - regular or inside Flexible Content.
2. Select "Uploaded to post" and WP uploader.
3. Add front-end form with the added Gallery field.

**Screenshots**
![screen1](https://github.com/user-attachments/assets/5a933346-4882-4960-ab5d-63edc2ad149d)
![screen2](https://github.com/user-attachments/assets/ad9a3677-e632-4586-866f-695b1542a18a)

**WordPress & ACF**
WordPress version: 6.6.2
ACF Pro version: 6.3.10
ACF add-ons: none

**Comment by acf-extended** [comment]
Hello!

Please see my answer on the [support thread here](https://wordpress.org/support/topic/uploaded-images-are-not-visible-in-the-gallery-field-on-front-end/#post-18208756).

Thanks!

Regards.

**Comment by VladNov** [comment]
Great, thank you!
