### ISSUE TITLE
Ajax Submission - Bug File Uploads

### ISSUE THREAD

**Issue by frieddbm** [acf-extended/ACF-Extended#134]
When submitting a form on "post_update" as ajax, every new file will be uploaded again until the form would be reloaded "hard".

**WordPress & ACF**
WordPress version: 6.7
ACF Pro version: 6.3.11
ACFE: 0.9.0.9

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback!

I'm not sure to fully understand what "submitting a form on 'post_update' as ajax" means.

If you're talking about the ACF Extended Front-end Form module ([see documentation](https://www.acf-extended.com/features/modules/forms)), then the "Ajax Submission" is an ACF Extended Pro feature.

Unfortunately, I cannot provide support for Pro feature on this channel. Please post a ticket fro myour [Account Dashboard](https://www.acf-extended.com/account) instead.

Thanks!

Regards.

**Comment by frieddbm** [comment]
Lieber Empfänger, vielen Dank für die eingehende Nachricht.

Nachrichten werden unter den folgenden Arbeitszeiten beantwortet:
Mo. - Do.: 08:00 - 9:00 Uhr MEZ sowie 17:00 - 18:00 Uhr MEZ
Fr.: 08:00 - 09:00 Uhr MEZ sowie 14:00 - 15:00 MEZ
ausgenommen österreichische Feiertage

Besten Dank,
Stefan Fried

**Comment by acf-extended** [comment]
Thank you! :)
