### ISSUE TITLE
Block Editor field styles possibly overriding custom editor styles in 6.7.1 block editor due to specificity?

### ISSUE THREAD

**Issue by jfr-codemonkey** [acf-extended/ACF-Extended#137]
**Describe the bug**
Block editor changes in 6.7.1 have introduced major specificity reduction using the :where() selector. 

This has resulted in some styles loaded in editor via load-styles.php gaining higher specificity, most notably this bit, which is overriding my custom image sizing.:

.block-editor__container img {
height: auto;
max-width: 100%;
}

which i was able to track to:
wp-content/plugins/acf-extended-pro/pro/assets/inc/block-editor/block-editor-6.5.css

According to source code this file seems to be used by the block editor field and should not interfere with block editor.

**To Reproduce**
Load custom editor styles applying image size via add_editor_style(), observe as it gets overriden due to higher specificity.

**Expected behavior**
Block editor field styles should not override block editor styles.

**Screenshots**
![image](https://github.com/user-attachments/assets/d880f337-2988-4992-a3c9-9183832d34ae)

**WordPress & ACF**
WordPress version: 6.7.1
ACF Pro version: 6.3.11
ACF add-ons:  Advanced Custom Fields: Extended Pro 0.9.0.9,  Advanced Custom Fields Multilingual

**Comment by acf-extended** [comment]
Hello,

The Block Editor is a ACF Extended Pro feature. Unfortunately, I cannot provide support for Pro features here. Please open a ticket from your [Account Dashboard](https://www.acf-extended.com/account) instead.

Thanks!

Regards.
