### ISSUE TITLE
Bulk Disable / Enable Field Groups

### ISSUE THREAD

**Issue by PaulMorel** [acf-extended/ACF-Extended#20]
**Is your feature request related to a problem? Please describe.**
No problem, just a quality of life improvement

**Describe the solution you'd like**
I think it could be nice to have an Enable and Disable option in the Bulk Actions on the Field Groups screen. For example if I want to disable 2 or more field groups at the same time.

**Comment by acf-extended** [comment]
Hello,

Sorry for the late answer! I added the feature request in Trello Board: https://trello.com/c/Z79H8Vz9/98-field-groups-add-new-mass-actions-like-export-json-php-autosync-php-json-activate-deactivate

I cannot give you a precise release ETA, but it "shouldn't be" very hard to achieve :)

Have a nie day!

Regards.

**Comment by acf-extended** [comment]
Hello,

I'm closing this ticket since the feature request has been added to the Trello Board: https://www.acf-extended.com/roadmap

Have a nice day!

Regards.
