### ISSUE TITLE
acfe-modal-overlay zindex issue

### ISSUE THREAD

**Issue by MrCarlLister** [acf-extended/ACF-Extended#22]
**Describe the bug**
zindex for .acfe-modal-overlay is higher than WordPress' own media gallery upload modal (.media-modal). So when you want to use the image gallery uploader in tandum with **Layouts Modal: Edition** setting, the gallery modal appears behind the ACFE modal.

**To Reproduce**
Issue occurs when using the **Layouts Modal: Edition** setting and the image field and media uploader setting

**Expected behavior**
Media gallery modal (.media-modal) should remain the higher zindex number of the two

**Screenshots**
![Screen Shot 2020-02-11 at 16 01 58](https://user-images.githubusercontent.com/8514103/74254105-e583d500-4ce7-11ea-8a6f-e1c09c69be8f.png)

**WordPress & ACF**
WordPress version: 5.3.2
ACF Pro version: 5.8.7
ACF add-ons: ACF Extended 0.8.4.5

**Comment by acf-extended** [comment]
Hello,

Thanks for the report! This has been fixed in the latest 0.8.4.6 patch. Please update the plugin :)

Have a good day!

Regards.
