### ISSUE TITLE
Advanced Link - filter

### ISSUE THREAD

**Issue by MrCarlLister** [acf-extended/ACF-Extended#23]
**Describe the bug**
As per instructions, I can add additional fields to the Advanced Link field as per

 ```
add_filter('acfe/fields/advanced_link/fields/name=button_test', 'my_acf_advanced_link_fields', 10, 3);
 function my_acf_advanced_link_fields($fields, $field, $value){
    
    /**
     * @array $fields   Sub fields array
     * @array $field    Advanced Link field
     * @array $value    The field values
     */
    
    $fields[] = array(
        'prefix'    => $field['name'],
        'name'      => 'my_field',
        'key'       => 'acfe_advanced_link_my_field',
        'label'     => 'My field',
        'type'      => 'true_false',
        'ui'        => true,
        'value'     => isset($value['my_field']) ? $value['my_field'] : ''
    );
    
    return $fields;
    
 }
```

However, data is not being saved.

**To Reproduce**
As above, add a custom field to an Advanced Link field and try and save data to it.

**Expected behavior**
Data to be stored and returned (front end when querying & backend when editing the field)

**Screenshots**
N/A

**WordPress & ACF**
WordPress version: 5.3.2
ACF Pro version: 5.8.7
ACF add-ons: ACF:E 0.8.4.6

**Comment by acf-extended** [comment]
Hello,

Thanks for the report! You are right, the instructions are wrong, you should use `'value' => isset($field['value']['my_field']) ? $field['value']['my_field'] : ''`. I'll rework that part of the field to make it easier. I also see there is a CSS problem on the "Close" button once inside the Advanced Link modal.

I added it to the Trello Board: https://trello.com/c/gOS9mO6G/108-advanced-link-custom-fields-values-problem

Have a nice day!

Regards.

**Comment by MrCarlLister** [comment]
This did not work for me.

The field is still not saving the data. When I save, all default fields save but the custom field returns to default.

```
add_filter('acfe/fields/advanced_link/fields/name=button', 'my_acf_advanced_link_fields', 10, 3);
function my_acf_advanced_link_fields($fields, $field, $value){
    
    /**
     * @array $fields   Sub fields array
     * @array $field    Advanced Link field
     * @array $value    The field values
     */
    
    $fields[] = array(
        'prefix'    => $field['name'],
        'name'      => 'my_field',
        'key'       => 'acfe_advanced_link_my_field',
        'label'     => 'My field',
        'type'      => 'true_false',
        'ui'        => true,
        'value' => isset($field['value']['my_field']) ? $field['value']['my_field'] : ''
    );
    
    return $fields;
    
}
```

**Comment by acf-extended** [comment]
Hello,

Yeah sorry, I was talking about the admin page modal. On my side, data is saved, but you're right it is not correctly returned. I've scheduled a field rework for the next patch which will fix all those issues. I'll let you know as soon as it's out.

Sorry for the inconvenience.

Regards.

**Comment by MrCarlLister** [comment]
> Hello,
> 
> Yeah sorry, I was talking about the admin page modal. On my side, data is saved, but you're right it is not correctly returned. I've scheduled a field rework for the next patch which will fix all those issues. I'll let you know as soon as it's out.
> 
> Sorry for the inconvenience.
> 
> Regards.

Any ideas on when this will be implemented? I've managed to use the following that at least updates and save changes (admin), but I still can't use the data on the frontend, the custom key & value aren't returned;

```
add_filter('acfe/fields/advanced_link/fields/name=button', 'my_acf_advanced_link_fields', 10, 3);
function my_acf_advanced_link_fields($fields, $field, $value){
    
    /**
     * @array $fields   Sub fields array
     * @array $field    Advanced Link field
     * @array $value    The field values
     */
    
    $fields[] = array(
        'prefix'    => $field['name'],
        'name'      => 'my_field',
        'key'       => 'acfe_advanced_link_my_field',
        'label'     => 'My field',
        'type'      => 'true_false',
        'ui'        => true,
        'value'     => isset($value['my_field']) ? $value['my_field'] : ''
    );
    
    return $fields;
    
}
```

**Comment by acf-extended** [comment]
Hello,

I'm sorry for the delayed patch, I'm currently really busing working on it, and it takes a bit more time than expected. The Advanced Link fix is ready tho. You can apply the fix manually, as it will be the code that will be used in the next patch.

Here is the Gist: https://gist.github.com/acf-extended/33cbbb51137c48be17fd19241a648f6b

You'll find one PHP file, one CSS file and one JS file. Instructions to apply the patch are written at the top of each files. Please remember the flush your browser cache before using the patch (there are new CSS & JS code).

Note: You'll see that instructions to add your own fields have been updated. The new hook to use is the following. The old one will still work, but you should use this one :) 

Please note that the custom sub fields declarations have been enhanced, and you don't need to set the `prefix` and `value` keys anymore. It's now automatically processed by the field.

```
add_filter('acfe/fields/advanced_link/sub_fields/name=advanced_link', 'my_acf_advanced_link_sub_fields', 10, 3);
function my_acf_advanced_link_sub_fields($sub_fields, $field, $value){
    
    /**
     * @array $sub_fields   Sub fields array
     * @array $field        Advanced Link field
     * @array $value        Advanced Link values
     */
    
    $sub_fields[] = array(
        'name'      => 'my_field',
        'label'     => 'My field',
        'type'      => 'true_false',
        'ui'        => true
    );
    
    return $sub_fields;
    
}
```

Tested on a blank WP install with ACF Pro & ACF Extended 0.8.4.6.

Have a nice day!

Regards.

**Comment by MrCarlLister** [comment]
> Hello,
> 
> I'm sorry for the delayed patch, I'm currently really busy working on it, and it takes a bit more time than expected. The Advanced Link fix is ready tho. You can apply the fix manually, as it will be the code that will be used in the next patch.
> 
> Here is the Gist: https://gist.github.com/acf-extended/33cbbb51137c48be17fd19241a648f6b
> 
> You'll find one PHP file, one CSS file and one JS file. Instructions to apply the patch are written at the top of each files. Please remember the flush your browser cache before using the patch (there are new CSS & JS code).
> 
> Note: You'll see that instructions to add your own fields have been updated. The new hook to use is the following. The old one will still work, but you should use this one :)
> 
> Please note that the custom sub fields declarations have been enhanced, and you don't need to set the `prefix` and `value` keys anymore. It's now automatically processed by the field.
> 
> ```
> add_filter('acfe/fields/advanced_link/sub_fields/name=advanced_link', 'my_acf_advanced_link_sub_fields', 10, 3);
> function my_acf_advanced_link_sub_fields($sub_fields, $field, $value){
>     
>     /**
>      * @array $sub_fields   Sub fields array
>      * @array $field        Advanced Link field
>      * @array $value        Advanced Link values
>      */
>     
>     $sub_fields[] = array(
>         'name'      => 'my_field',
>         'label'     => 'My field',
>         'type'      => 'true_false',
>         'ui'        => true
>     );
>     
>     return $sub_fields;
>     
> }
> ```
> 
> Tested on a blank WP install with ACF Pro & ACF Extended 0.8.4.6.
> 
> Video: https://i.imgur.com/NqrWu7o.mp4
> 
> Have a nice day!
> 
> Regards.

Appreciate your work and time putting this fix together for me! This seems to have resolved the problem.

Thanks again for all your help!

**Comment by acf-extended** [comment]
Hello,

Just to let you know that the latest 0.8.5 Fixed this issue.

Have a nice day :)

Regards.
