### ISSUE TITLE
Tabs with Conditional Logic when cloning flex layout are not hidden when they should be.

### ISSUE THREAD

**Issue by Hube2** [acf-extended/ACF-Extended#24]
**Describe the bug**
When cloning a flexible content layout, tabs that should be hidden by conditional logic are not hidden.

**To Reproduce**
Create a flex field and enable cloning. Create a true/false field. Create a tab field that is conditional on the true/false field being checked and add fields into the tab. Edit a post and add the layout, tab is hidden. Clone the layout, tab and fields in the clone are visible until you toggle the true false field on and off.

**Expected behavior**
Cloned tab field is hidden because of conditional logic

**Screenshots**
na

**WordPress & ACF**
WordPress version: 5.3.2
ACF Pro version: 5.8.7
ACF add-ons:

**Comment by acf-extended** [comment]
Hello @Hube2!

Thanks for the feedback! I'll run some tests and see if I can add the fix in the next patch. I will keep you updated!

Regards.

**Comment by acf-extended** [comment]
Hello,

Just to let you know that this bug will be fixed in the next patch. Trello task: https://trello.com/c/TcIbYCr6/138-flexible-content-clone-fixed-tabs-with-conditional-logic-not-hidden-when-they-should-be

Regards.

**Comment by acf-extended** [comment]
Hello,

Just to let you know that the latest 0.8.5 Fixed this issue.

Have a nice day :)

Regards.
