### ISSUE TITLE
How can i import a form (json) from a plugin ?

### ISSUE THREAD

**Issue by quasiperfect** [acf-extended/ACF-Extended#25]
thanks for your plugin i really love it :)

i have created some forms and i want to use them in a plugin so on activation i need to create the forms and on deactivation/uninstall remove the forms

any suggestions on how i could do that ?

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback! I'm glad that you enjoy ACF Extended :)

I have a task about that specific feature request: https://trello.com/c/hMupHofg/30-add-developers-functions-class-to-easily-use-acf-acf-extended-tools-import-sync

In the next patch, you'll able to easily import forms by simply using `acfe_import_dynamic_form($args|$json)`. I'll write you an example once it's up!

Have a nice day.

Regards.

**Comment by quasiperfect** [comment]
@acf-extended thanks for your response.
would be great to be able to import all types of json (form, fields, options page etc) from code.

**Comment by Pilotin** [comment]
Hello,

Well this is exactly what's suggested in the task :D

You can already import them dynamically, but you'll have to dig in the code. The PHP helpers which will make it easier will come, but later.

Regards.

**Comment by acf-extended** [comment]
Hello,

Well this is exactly what's suggested in the task :D

You can already import them dynamically, but you'll have to dig in the code. The PHP helpers which will make it easier will come, but later.

Regards.

**Comment by acf-extended** [comment]
Hello,

I'm closing this ticket since the feature request has been added to the Trello Board: https://www.acf-extended.com/roadmap

Have a nice day!

Regards.
