### ISSUE TITLE
Timber/twig support

### ISSUE THREAD

**Issue by bobhuf** [acf-extended/ACF-Extended#26]
Hello,

Is there any chance of adding [Timber/twig](https://github.com/timber/timber/) support for Flexible Content layout rendering and dynamic preview?

Thanks!

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback. This is something I haven't looked at yet. I don't use Timber/twig personally, but one of my contributor does and will most probably come with a solution for this.

I don't really have an ETA yet, but I've added the task to the Trello Board: https://trello.com/c/0CEJHcej/160-flexible-content-add-timber-twig-support-for-dynamic-render-preview

Have a nice day!

Regards.

**Comment by amustill** [comment]
Integration with Timber is a must-have feature for our team, as we build all our themes using it. We're starting on our journey of integrating ACF Extended in to our builds and so far have come up with the following pattern to integrate the two.

index.twig
```twig
<h1>{{ post.title }}</h1>

{{ fn('the_flexible', 'sections') }}
```

layouts/media-object/template.php
```php
<?php

$context = Timber\Timber::get_context();
$context['row'] = get_row(true);
$context['is_preview'] = $is_preview;

Timber\Timber::render('layouts/media-object/template.twig', $context);
```

layouts/media-object/template.twig
```twig
<div class="media-object">
    <div class="media-object__img">
        <img src="{{ Image(row.image).src }}" alt="">
    </div>
    <div class="media-object__body">
        {{ row.name }}
    </div>
</div>
```

This allows use of both dynamic preview and rendering from the same templates.

The pattern is simple and could be extended, potentially by extending Timber itself. We would love to see a more feature-complete integration and are happy to help with that moving forward.

**Comment by nlemoine** [comment]
I came up with a slightly different solution. 

Trick the template filter so it always returns an empty template: 
```php
add_filter('acfe/flexible/render/template', function($acfe_flexible_render_template, $field, $layout, $is_preview) {
    return 'empty.php';
}, 10, 4);
```

Then render your Twig template:
```php
add_action('acfe/flexible/render/before_template', function($field, $layout, $is_preview) {
    $context = Timber::get_context();
    $name = str_replace('_', '-', $layout['name']);
    $context['block'] = get_row(true);
    $context['is_preview'] = true;
    Timber::fetch(sprintf('views/blocks/%s.html.twig', $name), $context);
}, 10, 3);
```

I think a simple "pre render" filter placed at [the very beginning of `acfe_flexible_render_layout_template`](https://github.com/acf-extended/ACF-Extended/blob/550fac109079f9faa7f2fadb774310f51bd8432b/includes/core/helpers.php#L166): 
```php
$output = apply_filters('acfe/flexible/pre_render/template', '', $field, $layout, $is_preview);`
if(!empty($output)) {
    echo $output;
    return;
}
```
Would allow developers to shortcut the whole template rendering system below.

**Comment by acf-extended** [comment]
Hello,

I'm closing this ticket since the feature request has been added to the Trello Board: https://www.acf-extended.com/roadmap

Have a nice day!

Regards.
