### ISSUE TITLE
json sync categories?

### ISSUE THREAD

**Issue by yangkennyk** [acf-extended/ACF-Extended#3]
Is it possible to also json sync field group categories? 

The issue is that I need to pull down from staging after the client makes changes but I lose acf categories that I assign locally.

**Comment by yangkennyk** [comment]
Just to add to this.

My current process is
1. Pull down locally with migrate db pro
2. rename the acfe-php folder so it's not injecting the fields
3. sync locally with json sync
4. rename the acfe-php folder so it's synced back up.

**Comment by acf-extended** [comment]
Hello,

Yeah, someone already requested this feature, it will be added soon. How it will work:

- Categories will be set in the field group Json during the export process
- When you'll import a field group with categories inside the Json, the field group will have the categories set
- If the category doesn't exists, it will be created during the import

**Comment by acf-extended** [comment]
Hello yangkennyk,

Just to let you know that the latest ACF Extended 0.8.3 Update added this feature! Field groups categories will now follow the field group export/import process.

Regards.
