### ISSUE TITLE
Acf forms problem

### ISSUE THREAD

**Issue by pathokdar** [acf-extended/ACF-Extended#30]
I use acfe form to create a post but everytime someone create a new post it also create a page with post title. How can i disable that function. please fix the issue.Buy the way it's a very good plugin. Thank you.

**Comment by acf-extended** [comment]
Hello,

This is weird behavior. Are you sure that you have only 1 action in your form? Is it configured properly? Can you share a screenshot?

Do you use `acf/save_post` hook somewhere in your code?

Regards.

**Comment by acf-extended** [comment]
Hello,

Any news about that problem?

Regards.

**Comment by robinvibs10** [comment]
I have the same issue,,

I am using ACF extended dymanic form, 
used the form shortcode in an elementor popup..
with 2 actions (create post and send email).
but, every time someone create a new post it also create a page with post title. (see image below)
![image](https://user-images.githubusercontent.com/18256271/78950523-95679a00-7b01-11ea-92fe-7296433fb068.png)

also, I have ACF select field with conditional logic to show another field, but it is not working on the form.. (see image)..

![image](https://user-images.githubusercontent.com/18256271/78950627-f1322300-7b01-11ea-9c37-ccf4f960cdd8.png)

I hope this bugs will be fix soon..

Regards,

**Comment by acf-extended** [comment]
Hello,

The problem come from Elementor + YOAST having some nasty problem with shortcodes & `wp_insert_post()`. See related topic: https://wordpress.org/support/topic/infinite-loop-when-saving-custom-post/

I opened an issue on both Elementor & YOAST github

Elementor bug report: https://github.com/elementor/elementor/issues/10998
YOAST bug report: https://github.com/Yoast/wordpress-seo/issues/14643

A fix will included in the next ACF Extended patch, meanwhile you can apply the fix yourself following this instructions:

In the file: `/acf-extended/includes/modules/form/actions/post.php` `line:300`

Add the following code:

`add_filter('wpseo_should_index_links', '__return_false');`

Right before this part:

`$_post_id = wp_insert_post(array( ...`

Have a nice day!

Regards.

**Comment by acf-extended** [comment]
Hello,

Just to let you know that the latest 0.8.5.5 update fix this issue :)

Have a nice day!

Regards.
