### ISSUE TITLE
ACFE Post Type Labels + WPML

### ISSUE THREAD

**Issue by PaulMorel** [acf-extended/ACF-Extended#32]
**Describe the bug**
Labels from post types created with ACFE don't seem to be translatable.

**To Reproduce**
1. Install ACF, ACFE & WPML.
2. Create a new post type with ACFE
3. Scan theme or plugin with WPML (or Locotranslate)
4. Try to translate post label

**Expected behavior**
I have a bilingual site with french and english editors and I'd like to be able to translate a post type's labels. 

For example the string "Add New Event" in the admin panel should be translated to "Ajouter un nouvel événement" for our french editors, however WPML nor LocoTranslate seem to be able to scan for these strings.

**WordPress & ACF**
WordPress version: 5.3.2
ACF Pro version: 5.8.9
ACF add-ons: 0.8.5

At a glance, if you do PHP export, the label strings don't have a text domain attached to them. That might be part of the problem.

**Comment by acf-extended** [comment]
Hello,

Sorry for the late answer. The next update will add multilang compatibility features for WPML & PolyLang. All ACF Extended modules will be compatible: Post Types, Taxonomies, Options Pages & Block Types.

Modules labels will be dynamically registered for WPML and/or Polylang, you'll be able to directly translate them from your preferred plugin without having to scan files.

Note: ACF Extended will also have an ACF Options Page - Post ID compatibility feature for both WPML & Polylang out of the box.

Regards.

**Comment by PaulMorel** [comment]
Awesome! Great to hear support for Polylang too. I much prefer Polylang over WPML.

**Comment by acf-extended** [comment]
Hello,

The latest ACF Extended 0.8.6.5 update added this feature!

Have a nice day.

Regards.
