### ISSUE TITLE
ACF star rating field

### ISSUE THREAD

**Issue by wpsumo** [acf-extended/ACF-Extended#35]
**Is your feature request related to a problem? Please describe.**
Add a new field type ACF star rating field.

**Describe the solution you'd like**
Used this which works great: https://github.com/kevinruscoe/acf-star-rating-field

**Comment by acf-extended** [comment]
While the feature looks interesting, it is also tied to FontAwesome to display the stars icons. FontAwesome is not packaged with ACF Extended, so I cannot use it the same way this plugin does it (the plugin enqueue FontAwesome CDN BTW).

I'll probably need to find some nice SVG, and even better, let user customize the SVG himself.

I'm adding it to the Trello: https://trello.com/c/k3QPfSNj/181-add-star-rating-field

Have a nice day!

Regards.

**Comment by alriksson** [comment]
>While the feature looks interesting, it is also tied to FontAwesome to display the stars icons.

It is not, you can decide whatever img or svg to output. As you can select to print the value as number. In the frontend, you can assign full, half and empty icons with svg or image field.

There is no need to include font awesome package, only wp-admin is using fa icons but frontend doesn't need to. But would prefer backend to just use svg instead of loading a package as you say.

**Comment by acf-extended** [comment]
Hello,

The plugin is tied to FontAwesome and doesn't let you choose to use SVG or FontAwesome. It embeds FontAwesome in the backend all the time. The return value for the front-end is an another story.

Regards.

**Comment by alriksson** [comment]
Correct it embed font awesome in backend and me neither like that. 

Yes, correct.

>I would prefer an SVG only solution.

Yes please but the option to chose custom svg as well, inlined or image tag.

**Comment by acf-extended** [comment]
Hello,

I'm closing this ticket since the feature request has been added to the Trello Board: https://www.acf-extended.com/roadmap

Have a nice day!

Regards.
