### ISSUE TITLE
Code Field may not initialize correctly

### ISSUE THREAD

**Issue by Hube2** [acf-extended/ACF-Extended#36]
**Describe the bug**
It is possible for the code field not not initialize properly if the class file is loaded before ACF set up field types.

**To Reproduce**
Very difficult to reproduce, I cannot give steps. Sorry. I just know it can happen and it drove me nuts trying to figure out why my admin was crashing on only one site. Took me 6 hours of debugging to figure out why.

Here is the beginning of your class
```
class acfe_field_code_editor extends acf_field{
    
    function __construct(){
        
        $this->name = 'acfe_code_editor';
        $this->label = __('Code Editor', 'acfe');
        $this->category = 'content';
        $this->defaults = array(
            'default_value'	=> '',
			'placeholder'   => '',
			'mode'          => 'text/html',
			'lines'         => true,
			'indent_unit'   => 4,
			'maxlength'		=> '',
			'rows'			=> '',
			'max_rows'      => ''
        );
        
        // acf field types may not be initialized when this runs
        $this->textarea = acf_get_field_type('textarea');
        
        parent::__construct();
        
    }
```
I don't know if this is the solution you want but this is how I corrected my issue
```
<?php 
  
  // If this file is called directly, abort.
  if (!defined('WPINC')) {die;}
  
  if (class_exists('acf_field')) {
  
    if(!class_exists('ssi_field_code_editor')) {
    
      class ssi_field_code_editor extends acf_field {
        
        public function __construct() {
          $this->name = 'ssi_code_editor';
          $this->label = __('Code Editor', 'ssi');
          $this->category = 'content';
          $this->defaults = array(
            'default_value'  => '',
            'placeholder'   => '',
            'mode'          => 'text/html',
            'lines'         => true,
            'indent_unit'   => 4,
            'maxlength'    => '',
            'rows'      => ''
          );
          parent::__construct();
          add_action('acf/init', array($this, 'acf_init'));
        } // end public function __construct
        
        public function acf_init() {
          $this->textarea = acf_get_field_type('textarea');
        }
```

**Comment by acf-extended** [comment]
Hello @Hube2,

Thanks for the feedback. I'm not quite sure to really understand what you're trying to achieve tho. Are you saying that when you active ACF Extended, it crashes your admin? Or are you trying to make your own field, without ACF Extended? As I can see you use `ssi_code_editor` as field type in your class.

ACF Extended includes fields on the `acf/include_field_types` hook (priority `99`), which is the correct hook to add new fields (and call others, in this case).

I think the problem come from your class. What is the hook you're using to include your class?

BTW, do you have any debug log to share when the admin crash?

Thanks in advance,

Have a nice day!

Regards.

**Comment by Hube2** [comment]
Thank you for waking me up. Yes, I was trying create a code area field from your example with a few changes.. I needed one for a project without all the other things that your plugin adds. I like the one you provide because it includes the WP Built in code mirror script rather than loading it independently or using some other code editor script.  Quite honestly, I should have realized that I needed to include the file on the hook and not just include it. You'd think that after all these years of working with ACF that I would not make these stupid mistakes.
