### ISSUE TITLE
Advanced Link field Required doesn't pass validation with Post selection

### ISSUE THREAD

**Issue by matthisamoto** [acf-extended/ACF-Extended#37]
**Describe the bug**
Using an Advanced Link field and setting it to Required, when I edit the page where it appears, the page will not save and the error says there is no value for the field.
`Validation failed. 1 field requires attention`

**To Reproduce**
Use Advanced Link field
Set field to Required
Choose Post in the dialog window and select post object
Attempt to save page, see error

**Expected behavior**
Pass validation, save page

**Screenshots**
<img width="288" alt="Screen Shot 2020-04-21 at 3 48 10 PM" src="https://user-images.githubusercontent.com/547172/79912400-980e9d00-83e7-11ea-9a9c-ac278dca47d6.png">

<img width="741" alt="Screen Shot 2020-04-21 at 3 48 17 PM" src="https://user-images.githubusercontent.com/547172/79912397-97760680-83e7-11ea-8da2-3de7e16c07ae.png">

**WordPress & ACF**
WordPress version: 5.4
ACF Pro version: 5.8.9
ACF add-ons: Only this, version 0.8.5.5

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback! I just checked, and you're right the required validation doesn't work correctly. I'm adding the ticket to the Trello Board: https://trello.com/c/3uS5oaPU/188-advanced-link-requried-field-validation-fail

It will be fixed in the next patch.

Sorry for the inconvenience.

Regards.

**Comment by acf-extended** [comment]
Hello,

I fixed the issue. The patch is coming. Meanwhile you can apply the fix yourself using the following instructions:

In the file `acf-extended/includes/fields/field-advanced-link.php` `line:495`. Replace:

`if((acf_maybe_get($value, 'post') || acf_maybe_get($value, 'term')) && !acf_maybe_get($value, 'url'))`

With:

`if((acf_maybe_get($value, 'type') === 'url' && !acf_maybe_get($value, 'url')) || (acf_maybe_get($value, 'type') === 'post' && !acf_maybe_get($value, 'post')) || (acf_maybe_get($value, 'type') === 'term' && !acf_maybe_get($value, 'term')))`

Sorry for the inconvenience.

Have a nice day!

Regards.

**Comment by acf-extended** [comment]
Hello,

Just to let you know that the latest ACF Extended 0.8.6 update fix this issue!

have a nice day :)

Regards.
