### ISSUE TITLE
acf-extendend.js error

### ISSUE THREAD

**Issue by robinvibs10** [acf-extended/ACF-Extended#38]
I am using latest version of WP, elementor pro and ACFE

but I always get this error below..
How will I fix this?

![acfe error](https://user-images.githubusercontent.com/18256271/79928897-cdae9700-8476-11ea-892f-5049b4f152ce.JPG)

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback. Can you please let me know in which condition this error appear?

- Is it front-end with Elementor? Does the page include a Dynamic Form?
- Back-end with Elementor?

Thanks in advance.

Regards.

**Comment by acf-extended** [comment]
Hello,

The next patch will enhance the detetion of `acf` in the JS file, which will avoid this error on specific cases like yours.

Regards.

**Comment by acf-extended** [comment]
Hello,

Just to let you know that the latest ACF Extended 0.8.6 update included an enhancement which could resolve your problem!

have a nice day :)

Regards.
