### ISSUE TITLE
filter advanced link post types?

### ISSUE THREAD

**Issue by yangkennyk** [acf-extended/ACF-Extended#4]
Is there an easy way to filter the advanced link post types that are returned?

**Comment by acf-extended** [comment]
Hello,

You can filter the post types using the following hook: `acf/load_field/key=post`. However, you'll have trouble to target a specific advanced link field (by name or key for example).
I'll enhance the field by letting you set post type/taxonomy filter directly in the advanced link field settings in a future patch.

I'll let you know as soon as the patch is up.

Regards.

**Comment by acf-extended** [comment]
Hello yangkennyk,

Just to let you know that the latest ACF Extended 0.8.3 Update added this feature as a field setting. You can now setup the post types & taxonomy terms of your choice, directly in the advanced link field settings! :)

Regards.
