### ISSUE TITLE
In a flexible content modal layout settings, the conditionnal fields contain the values of previously deleted layout at the same position instead of the defaults when first saved hidden 

### ISSUE THREAD

**Issue by verteb** [acf-extended/ACF-Extended#41]
**Describe the bug**
Let me explain my setup first: I made a grid with a flexible content field that has containers that contain columns. The containers use ACF-Extended modal settings and I have of lot of fields in that modal. To avoid saving a bunch of data when I only need the default settings, I put all the settings fields in a conditionnal field group that is toggled with a "Customize" checkbox at the top of the modal.

**To Reproduce**
Let's say I create 2 containers, customize both of them and save the page. After that, I delete the second container and save the page again. Next I create a new second container, I **don't** customize it and I save the page. After that I open the settings of my new second container and check the customize checkbox. All the customizations of the previously deleted second container are there instead of the defaults. I know I could simply create a container and check the customize checkbox right away to display default values and overwrite the old settings but the goal is to avoid saving useless data when I need to use the defaults...

**Expected behavior**
I should see the default values in the layout settings when I create a new layout instead of the previously deleted values of the layout settings that was at the same position in the page at some point in time.

See: advanced-custom-fields-pro/pro/fields/class-acf-field-flexible-content.php -> function update_value. Old rows are deleted when the layout changes in ACF but ACFE layout settings are not deleted. 

**WordPress & ACF**
WordPress version: 5.4
ACF Pro version: 5.8.9
ACF add-ons: none

**Comment by acf-extended** [comment]
Hello,

Thanks for the detailed report. I'll investigate it, but the update_row() & delete_row() is probably a good lead, as Layout Settings is a virtual clone created on the fly.

I'll keep you updated.

Regards.

**Comment by acf-extended** [comment]
Hello,

The problem come from the ACF logic with clones inside flexible content layouts. ACF doesn't delete clones data when the user remove a layout. I managed to reproduce your bug report with a simple clone inside a layout (tied to a conditional logic).

The clone field is kinda complex, and I prefer do not alter it. I would suggest to submit a bug report to ACF, so it can be managed natively.

Sorry for the inconvenience.

Regards.
