### ISSUE TITLE
Bidirectional on same-name field, same post-type

### ISSUE THREAD

**Issue by MrCarlLister** [acf-extended/ACF-Extended#43]
Not sure if this should already be do-able or not - if not I guess this is a feature request.

While editing Product A, I want to link Product B, C, & D (same post type) using the same relationship field. I figured, setting the relationship field to Bidirectional and not specifying a field in the dropdown would mean it would self-link (if that makes sense).

Should this be the case? Is this possible?

To clarify, the dropdown next the bidirectional option does not allow me to pick the current field.

**Comment by acf-extended** [comment]
Hello,

Just to let you know that the latest 0.8.6.3 Update added the self/multi bidirectional setting, allowing you to link a field on itself (and achieve what you're asking for).

Have a nice day!

Regards.

**Comment by MrCarlLister** [comment]
Fab - appreciate the quick turn around!
