### ISSUE TITLE
Having incompatibility issues when using with Advance Forms Pro by Hookturn

### ISSUE THREAD

**Issue by rovillesarate** [acf-extended/ACF-Extended#47]
**Describe the bug**
Getting Unidentified Offset 1 error on ACF decrypt when ACF Extended is active. Works when i disable the plugin. Using Advance Forms Pro to display frontend ACF Form.

Submitting form directly on the wp-admin does not cause any errors

**To Reproduce**
1. I am using a framework called themosis
2. Installed ACF PRO + ACF Extended + HookTurn Advance Form PRO
3. Create a Field and assign it to a Form at HookTurn Advance Form PRO\
4. On the frontend when you submit the form you get error Unidentified Offset 1
list($encrypted_data, $iv) = explode('::', base64_decode($data), 2); at line 4655 of plugins/advanced-custom-fields-pro/includes/api/api-helpers.php
5. If disable ACF Extended forms already submits and works properly
**Expected behavior**
Be able to submit the form from the frontend using Advanced Forms Pro while ACF extended is active

**Screenshots**
![Screen Shot 2020-06-23 at 12 45 05 AM](https://user-images.githubusercontent.com/2109352/85313118-5636cb80-b4ea-11ea-8b81-310981271679.png)

**WordPress & ACF**
WordPress version: 5.4.2
Advanced Custom Fields: Custom Database Tables | Version 1.0.5
Advanced Custom Fields: Extended | Version 0.8.6.3 by ACF Extended
Advanced Custom Fields: Signature | Version 1.0 by James Park
Advanced Custom Fields: Theme Code Pro | Version 2.5.0 by Hookturn with Ben Pearson
Advanced Custom Fields PRO | Version 5.8.12 by Elliot Condon
Advanced Forms Pro | Version 1.6.8 by Hookturn with Fabian Lindfors
Brizy | Version 1.0.126 by Brizy.io
Brizy Pro | Version 0.0.41 by Brizy.io

MU Plugin:  Themosis Framework Loader | Version 1.4.0

- Open SSL extension is active
- Error seems to affecting 
`$form = json_decode(acf_decrypt($_POST['_acf_form']), true);`
it is also possible that the validation is having conflict with the acf extended and advanced form pro
```
    // Validate the posted data, this validation has already been performed once over AJAX
    if ( acf_validate_save_post( true ) ) {
      $form = AF()->submission['form'];
      $args = AF()->submission['args'];
      $fields = AF()->submission['fields'];
      
      // Increase the form submissions counter
      if ( $form['post_id'] ) {
        $submissions = get_post_meta( $form['post_id'], 'form_num_of_submissions', true );
        $submissions = $submissions ? $submissions + 1 : 1;
        update_post_meta( $form['post_id'], 'form_num_of_submissions', $submissions );
      }
 
      do_action( 'af/form/before_submission', $form, $fields, $args );
```

**Comment by rovillesarate** [comment]
Whats weird is if i use a plugin called Black Bar. Everything suddenly works. I can already submit the form but when i deactivate the plugin. I am back to the previous problem.

**Comment by acf-extended** [comment]
Hello,

Thanks for the very detailed report. I'll install Advanced Forms (free) and see if I can reproduce the problem. I already had a chance to use/debug Advanced Forms, and I'm not really fan of how they code their plugin (they don't use existing ACF functions/methods and prefer rewrite them when everything is already available).

I'll keep you updated here.

Regards.

**Comment by acf-extended** [comment]
Hello,

So I found the problem, Advanced Forms is using the generic `$_POST['_acf_form']` key (which is used by ACF when submitting form, as well as ACF Extended). As I said in my previous answer, Advanced Forms isn't using the native ACF way to encrypt data that is stored in this key. Instead of using `acf_encrypt()` function, it uses it's own `base64_encode()`.

Here is how ACF & ACF Extended data looks like:

```aGh3UHRLVXYvblRZWUdocFJwODAyZCtKV3FCRjB6aDJxcUZuUU91RldMVHlxcTNuOFRiSmpTMzdBVGpkdlZ2eWk5eWg5WE5zdWd3UWk0Rk5vOVAvT25Hd1hJRXJIdjhzanNOT0V2TzJkSVpvaUNyYlhCZWNpSVB0dFhFbVN3eE5tN3BKeHRUQkhlUURnWUsrME1JQmZUYjFrWDg3dFB5OW1ESEpITzZLQUpzTkdmTWkzYVhkMndNSERydWR1cnFTTUt2R1RoK1pGVjRWckVTaWxONlIyV3diemU0ZTEwaEtSeVU2bUhrSjBUWTdoNVBMOWxNVFM5MTQ5VTFvZG9keEZ1dnlEK1plYldMVHV0b0xZRGhnTWswRlQwTStLQ1ZHRWc4dktqaHNtQTZTWXJOQi9tYWpzODJRdXdnVlRyTkZoTUpaU3FFTFQ4Vlp5aHVTNTY0Wm5BVU9Qc3k3NVlTWERtSWh2dlBOUENtWm9TWitDNHRuakhqanFPemVOc2ozZjFwR2ZzY3RIdnkycHg0V2krQ1ZUY2dDV1hTNjNyUzVKV3AydmtwYkM0bFBRRzNRWmdmZ0dvbldjUVVtNDRzNFBielJvZkJMOHlOdUQ1MUlNRG1Kd0V4aVgrOHdqRk1YWk5sa3hlY0Q5MWM1bERjSkZUTzlNS3dhV3Z4d2VGNXJFVm9BbTlrUEFxazc0enZPb0lCaHloQTNySm5VNG5TQzdveHd1VnZyM2IwZmxJT3dpaFZnZGQyUGI0Sk5qSHVTNW1XNEQrZGF1OW1IdHlhckUvQ0VhNlhTbWEraFVlTnZ5NHR5bTlWeHFDQTNBcVBMbHFYUk0wMmJkbXR2dG9RMFVWQlBETHpGanBjSlVELzYyU1BYbjVmbXRWdElQVTlvbXFXVGgyN1I0SUJNL3JDcVQxY3RGOE1zVHFLVFdWWktCZ1d6ZVA4Y0NMa0syS0NFQXY1dlpMM3FwTHNHTWJ1Z1p0ZWlMeSt5b3ZCbTdFcHV4bHpsZUE0NW5oQ1VVMFNTYmxxQ1FFb1ZVUm1WMHo4QnRJajA5N1c3MUM3ODViNit6ano3amtQSzFSalVkZWVQdHpYRlgrTnRQOWlzRDNZejZEVzdqM25mNjgwRXA3V3kvTjAvNTVvdWxxdjVuaFZRZ3ZiZm44TGwxK1pWajNrRkJaeGMyY3dzN3NLc2hkYWNYLzVibXZLUm9ITjJrSENrVHVQeUJZTVloekY3ZElkeUpGR1lxdSsvakNydnE5UmJrK0pHY1lLTVhBeG4xc3VjZVVEcUdEZ2daQjF3Q3VlQkZYMmc5WktmSnNHbkh3L1ZmaGxRSklsME9yZEU3RVAvUmIycmJ0R1dtenEweXFjTXpwUXR5c1BTTWJRMFdxcERsQyt4WjR2RTFEVjZKak5mU2lnNTZicWNqZDJ5bTFVVEZyVGFlMU5pWjBNK0xtWkFxdGFOUHhqS2NRZmpFNHdhcUM3TkU2b0JpZldYSzFQR1RSOUQ5YWlmN2ZLQTZmdnF0YW1YaEZPMlBZbWs2ak02MnM1aVA2VUpKOEFWMTZyZUx5YVdrWDJENEJyMWdoMzlrK0NzcUExUVYySWE1OExMWFl1TWgrbjV4RkVwNURoNlNHWHNRTVNxWmE2TzJ5Y2RCSjN5N1R2aFNuR0xnOEtBUzBUS1ZMbHRxR0JCQ3hkREhiUUx3NjdJbXZ4RHdtK2FYK045QzVDTEU1bFhyYnUyeGFlSTYrcURWeDRweTErRVg0OVYyQ3QwMVhlK0c4ek93eEpxWDVxTHZBUTNSUmZSS3NUb0gzOVVCQ24rb2RKRDlHQndIVTMwckozYUZNaldvajBDVFYzKzdjYk9aU2QyY1N6dU5pQ3FSdENPdExZQ2x1R2NEZ25LdGttZFVQaUdHRDg0R0RjRHpiai9DSVBhSkxURG0yOWhDVVd2akVqelU0Rno1S0RYeEhYQWcrR0lxT0krWElwRjdaclE3dVJqVTZLZzc1eW9JMk5kNlVSNlhISUxmOHpCQzVZdDlkZWlNZWxNWUUyNW9oYjFLbWlWdWtxZ2Q1czJPWjd0TG5HMCtBdTFkWWMyMUhLdXhYQlgzUGVXdzlPQjMyT2l0VWtEMEMyUHNBczJRSm5aOXYxaE01QUpJSTFGOXJEbnJtd3hCeTZqcThtUmMwZkYrN25IU01LSkI4eU9sT21hcFVWYkhyc3ZwRkVYR0c4Q3Z4VHA0ZDJFSGgxcFYvQ3FKZ2FvY3g5WllyZ0g0ZXRJeW0wcktkcGhCT3hMQWx2V25NZFFMRzNuWFpTalJYN21YZjIyOjoC1+9hXQNsxcA7W8GRmsiO```

Here is how Advanced Forms data looks like:

```eyJkaXNwbGF5X3RpdGxlIjpmYWxzZSwiZGlzcGxheV9kZXNjcmlwdGlvbiI6ZmFsc2UsImlkIjoiZm9ybV81ZWYxYzA1OWQ2NDE2IiwidmFsdWVzIjpbXSwic3VibWl0X3RleHQiOiJTdWJtaXQiLCJyZWRpcmVjdCI6Imh0dHA6XC9cL3d3dy5hY2YuZHZcL2Zvcm1cLyIsInRhcmdldCI6Imh0dHA6XC9cL3d3dy5hY2YuZHZcL2Zvcm1cLyIsImVjaG8iOnRydWUsImV4Y2x1ZGVfZmllbGRzIjpbXSwidXBsb2FkZXIiOiJ3cCIsImZpbHRlcl9tb2RlIjpmYWxzZSwibGFiZWxfcGxhY2VtZW50IjoidG9wIiwiaW5zdHJ1Y3Rpb25fcGxhY2VtZW50IjoibGFiZWwiLCJob25leXBvdCI6dHJ1ZX0=```

So yeah, I'll add an additional check to ensure ACF Extended doesn't try to decrypt this unconventional data. The fix will be added in the next patch.

Regards.

**Comment by acf-extended** [comment]
If you don't want to wait for the next, you can fix the issue by yourself, by following this instructions:

In the file `/acf-extended/includes/modules/form/form-front.php` `line:39`. After the following code:

```php
if(!acfe_form_is_front())
    return;
```

Add the following code:

```php
if(acf_maybe_get_POST('_acf_screen') !== 'acfe_form')
    return;
```

Regards.

**Comment by rovillesarate** [comment]
Thank you. This will be a lot of help. =)


*Roville Sarate*
Co-Founder, CTO

**Comment by acf-extended** [comment]
Hello,

The latest ACF Extended 0.8.6.5 update fixed this issue!

Have a nice day.

Regards.
