### ISSUE TITLE
Notice: Trying to access array offset on value of type bool (includes/modules/dev.php)

### ISSUE THREAD

**Issue by codemonkeynorth** [acf-extended/ACF-Extended#48]
**Describe the bug**
Notice warning in Admin panel: `Trying to access array offset on value of type bool /wp-content/plugins/acf-extended/includes/modules/dev.php on line 512`

**To Reproduce**
* set WP_DEBUG=true
* visit a post/page in admin that has ACF fields

**Expected behavior**
No noticed should be shown

**WordPress & ACF**
WordPress version: 5.4.2
ACF Pro version: 5.8.12
ACF add-ons: ACF Content Analysis for Yoast SEO, ACF Extended, Advanced Custom Fields: Image Aspect Ratio Crop

**Comment by acf-extended** [comment]
Hello,

It's weird that you see this error. 

- May I ask you PHP version?
- Can you take a screenshot of the ACF/WP meta dev mode (at the bottom of a Post in the Admin Area)?

Anyways, I'll add extra checks to avoid this warning in the next update.

Regards.

**Comment by codemonkeynorth** [comment]
Hi,

PHP 7.4

I can't show you a full screenshot as there are a lot of fields and also specifically some private content - however I can show you this portion. 

I'm wondering if the error relates to old fields that are no longer mapped (see `Undefined` entries - this would happen when deleting/replacing a flexible content row potentially I think)

![image](https://user-images.githubusercontent.com/20189985/86368543-34211400-bc75-11ea-9f10-e4a49e181a4a.png)

thanks
J.

**Comment by acf-extended** [comment]
Hello,

Yes, the `Undefined` fields are what trigger that warning in PHP 7.4 only. A fix will be added in the next ACF Extended Patch to avoid that.

Please note that WP will display this warning with PHP 7.4 when using `remove_meta_box()` function. See ticket: https://core.trac.wordpress.org/ticket/50019

ACF Extended use the `remove_meta_box()` function for the "Ajax Author Box" feature. So unless you disable that feature, you'll get a warning until the WP core is fixed.

Have a nice day.

Regards.

**Comment by acf-extended** [comment]
Hello,

The latest ACF Extended 0.8.6.5 update fixed this issue!

Have a nice day.

Regards.
