### ISSUE TITLE
options page sync

### ISSUE THREAD

**Issue by yangkennyk** [acf-extended/ACF-Extended#5]
way to sync option pages when a db is overwritten by a db pull from server site

**Comment by acf-extended** [comment]
Hello,

I'll add an option which will let you export an option page to PHP. This way you'll be able to register your option page directly in plugin/theme.

I'm also thinking about a PHP AutoSync feature for options pages/dynamic post types/taxonomies, but it's not quite ready yet.

I'll let you know as soon as the patch with manual PHP export is up!

Regards.

**Comment by acf-extended** [comment]
Hello yangkennyk,

Just to let you know that the latest ACF Extended 0.8.3 Update added the PHP export action for options page. So you can now keep your options page synced with PHP code!

Regards.
