### ISSUE TITLE
Maximum posts in  Bidirectional Relationship Fields

### ISSUE THREAD

**Issue by igorchernenko92** [acf-extended/ACF-Extended#52]
**Is your feature request related to a problem? Please describe.**
If i set maximum posts from one side of Bidirectional Relationship Fields, from other side you are able to add more than that number and all posts will be set into current one as well despite on the restriction set
**For example:** agent and properties (one to many), in properties max post(agents) set to 1. If i in two different agents set same property, in one property i will have two agents. 

**Describe the solution you'd like**
if i set two properties to one agent at least notify that max post from other side is set and you are trying to overlimit that number. 

<img width="1143" alt="github" src="https://user-images.githubusercontent.com/38693634/88165736-d867fc00-cc1e-11ea-9bdf-7266eb822e16.png">

**Comment by acf-extended** [comment]
Hello,

I'm closing this ticket since the feature request has been added to the Trello Board: https://www.acf-extended.com/roadmap

Have a nice day!

Regards.
