### ISSUE TITLE
Error in Location column in Field Group list with Attachment "All image formats"

### ISSUE THREAD

**Issue by Accudio** [acf-extended/ACF-Extended#55]
**Describe the bug**
"Warning: Illegal offset type in isset or empty" error in Field Group list for field group with one of the media groups for Attachment.
```Warning: Illegal offset type in isset or empty in /[...]/wp-content/plugins/acf-extended/includes/core/helpers.php on line 1410```
```Notice: Array to string conversion in /[...]/wp-content/plugins/acf-extended/includes/core/helpers.php on line 1425```

**To Reproduce**
Create Field Group with location rule of "Attachment is equal to All image formats". This also applies to "All video formats", "All text formats", "All application formats" and "All audio formats".

**Expected behavior**
Should return "Attachment = All image formats"

**WordPress & ACF**
WordPress version: 5.4.2
ACF Pro version: 5.8.12
ACF add-ons:
- ACFE 0.8.7;
- ACF Content Analysis for Yoast SEO 2.5;
- Advanced Custom Fields: Image Aspect Ratio Crop 3.4.0

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback! This will be fixed in the next patch.

Just a note on the new ACF 5.9 version: The ACF Extended "Location" column has been replaced with the native ACF "Location" column, so this issue doesn't occur on the latest ACF version.

Have a nice day!

Regards.

**Comment by acf-extended** [comment]
Hello,

Just a heads up, this issue has been fixed in the latest 0.8.7.1 update.

Have a nice day!

Regards.
