### ISSUE TITLE
Filter to disable adding HTML comments in get_flexible()

### ISSUE THREAD

**Issue by rcobiella** [acf-extended/ACF-Extended#56]
Is there a filter in place to prevent ACFE from adding the field labels in HTML comments in the front-end? I've been looking around to see if there's an option for it but haven't seen anything.

Thank you!

**Comment by acf-extended** [comment]
Hello,

I'm closing this ticket since the feature request has been added to the Trello Board: https://www.acf-extended.com/roadmap

Have a nice day!

Regards.
