### ISSUE TITLE
Call to undefined function after last update

### ISSUE THREAD

**Issue by flexelektro** [acf-extended/ACF-Extended#57]
After the last update to 0.8.7.1 i am getting this error while saving or updating my post types.
After returning to version 0.8.6.3 the error is gone.

Sorry for this messy bug report. I hardly use Wordpress, have no time to fix it on my own, and am quite in a hurry ... 

Fatal error: Uncaught Error: Call to undefined function acf_unarray() in /www/htdocs/w007a50e/wp-tdjml/wp-content/plugins/acf-extended/includes/fields/field-post-object.php:203 Stack trace: #0 /www/htdocs/w007a50e/wp-tdjml/wp-includes/class-wp-hook.php(289): acfe_field_post_object->update_value(Array, 223, Array) #1 /www/htdocs/w007a50e/wp-tdjml/wp-includes/plugin.php(249): WP_Hook->apply_filters('220', Array) #2 /www/htdocs/w007a50e/wp-tdjml/wp-content/plugins/advanced-custom-fields-pro-master/includes/acf-hook-functions.php(101): apply_filters_ref_array('acf/update_valu...', Array) #3 /www/htdocs/w007a50e/wp-tdjml/wp-includes/class-wp-hook.php(287): _acf_apply_hook_variations('220', 223, Array, '220') #4 /www/htdocs/w007a50e/wp-tdjml/wp-includes/plugin.php(206): WP_Hook->apply_filters('220', Array) #5 /www/htdocs/w007a50e/wp-tdjml/wp-content/plugins/advanced-custom-fields-pro-master/includes/acf-value-functions.php(185): apply_filters('acf/update_valu...', '220', 223, Array, '220') #6 /www/htdocs/w007a50e/wp-tdjml/wp-co in /www/htdocs/w007a50e/wp-tdjml/wp-content/plugins/acf-extended/includes/fields/field-post-object.php on line 203

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback. This is because the ACF function `acf_unarray()` was introduced in ACF 5.8.10 version and you're using a previous version. Updating your ACF Pro plugin will fix the issue.

I'll implement a compatibility fix in the next path.

Regards.

**Comment by acf-extended** [comment]
Hello,

Just a heads up, the latest 0.8.7.2 Update fixed this issue! Have a nice day.

Regards.
