### ISSUE TITLE
Use custom field as flexible content row title

### ISSUE THREAD

**Issue by bramchi** [acf-extended/ACF-Extended#58]
This idea came to mind when I discovered the 'Allow layout title edition' checkbox. It is a bit of an extended version of what that feature helps improve.

When you have several flexible content rows of the same layout type after eachother, it can become a bit unclear which is which. Manually setting the title of the row is a step in the right direction. But often I have a title field in the flexible content layout that is very relevant.

Wouldn't it be great if you could set the row title programmatically, by connecting it to one of the fields that is configured inside the flexible component layout? 

Maybe you could add a filter, similar to "acfe/flexible/thumbnail/name=flexible_content", that allows you to return the value of a custom field, to be used as the title. And maybe it could also pass through the name of the layout, so you can prefix it or append it to the dynamic title.

Looking forward to your response :-)

**Comment by apsolut** [comment]
Could default filter help ? Used to modify the $title HTML displayed at the top of each flexible content layout.
`acf/fields/flexible_content/layout_title`
https://www.advancedcustomfields.com/resources/acf-fields-flexible_content-layout_title/

**Comment by bramchi** [comment]
@apsolut Thanks for the interesting suggestion. That might work!

**Comment by acf-extended** [comment]
Hello,

Sorry for the late answer.

The solution provided by @apsolut is definitely the best way to achieve it.

I'm closing the ticket since ACF handle it by default.

Regards.

**Comment by bramchi** [comment]
Works like a charm indeed. Here is some example code to get others started.

```php
add_filter('acf/fields/flexible_content/layout_title', 'custom_flexible_content_title', 10, 4);
function custom_flexible_content_title( $title, $field, $layout, $i ) {
    switch ($layout['name']):
        case 'mm-hero';
            $title = $title . ' · ' . $field['value'][$i]['field_60534ca1037cb']['field_60534ca6037cc'];
            break;
        case 'mm-testimonial';
            $title = $title . ' · ' . $field['value'][$i]['field_6059eba8ed62a']['field_6059eba8ed62b'];
            break;
    endswitch;

    return $title;
}
```

It gets the value from a nested title field and appends it to the layout name. And with the help of some CSS I got it to look like this:

![flex-content-title](https://user-images.githubusercontent.com/3725476/114152113-2b552100-991e-11eb-867b-b11fe1b96f55.png)
