### ISSUE TITLE
Flexible content render templates, get_flexible returns ONLY the html comments

### ISSUE THREAD

**Issue by anobjectn** [acf-extended/ACF-Extended#59]
**Describe the bug**
the_flexible('fieldname') and get_flexible('fieldname') return only the HTML comment with the layout's label. Nothing from my template file outputs not even static elements and content. 

**To Reproduce**
Specify a php render template for a layout, e.g. `content-sections/testimonial-carousel.php` 

**Expected behavior**
Expecting template to render and out put markup and data

**WordPress & ACF**
WordPress version: 5.5.1
ACF Pro version: 5.9.1
ACF add-ons: 
Advanced Custom Fields: Extended
Advanced Custom Fields: Gravityforms Add-on
Advanced Custom Fields: Theme Code Pro

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback! There's probably something wrong in your Flexible Content configuration. The template should be correctly rendered on the front-end if the template file exists.

The Flexible Content: Layout Render features is used on by myself on dozen of websites, and hundreds of other users. Can you make sure the template file `content-sections/testimonial-carousel.php` exists in your theme? Can you share some screenshots of your Flexible Content configuration, see if everything's alright?

Thanks in advance.

Regards.

**Comment by acf-extended** [comment]
Hello,

I'm closing this ticket since there's no more information, and I didn't receive any other support ticket about that topic.

Regards.
