### ISSUE TITLE
Plugin Breaks WP admin when loading ACF field groups via acf_add_local_field_group()

### ISSUE THREAD

**Issue by qstudio** [acf-extended/ACF-Extended#60]
**Describe the bug**
This issue currently only appears when editing content in the admin - the admin does not load correctly, tinyMCE fails, and some field groups fail to load.

We hook into acf/init to add the exported fields groups with `acf_add_local_field_group()`

**To Reproduce**
Add a field group via `acf_add_local_field_group` hooked to `acf/init` and then edit a single post page with field group settings

The problem can be "fixed" by either disabling the acfe plugin - or removing the hooks used to load the acf field groups - but, clearly - the ideal is that both can play nicely together ;)

**Expected behaviour**
Normal admin and ACF group loading - instead, tinyMCE breaks and extra field groups are not loaded

**Screenshots**

**WordPress & ACF**
WordPress version: 5.5.1
ACF Pro version: 5.9.1
ACF add-ons: Extended v 0.8.7.3

The page load timesout here:

acf-pro/includes/acf-field-functions.php:1331 in the function `acf_get_field_ancestors()` is being called by acfe/includes/core/helper.php:454 at function `acfe_get_field_group_from_field()`

The issue appears to be that the groups loaded via `acf_add_local_field_group()` do not return the expected parent data - causing an endlesss loop of data loading...

**Comment by qstudio** [comment]
As a follow-up - removing the following filter "fixes" the issue:

`add_filter('acf/pre_render_fields', 'acfe_fields_wrapper_instructions', 10, 2);`

However, currently I cannot get this filter to remove using:

`\remove_filter( 'acf/pre_render_fields', 'acfe_fields_wrapper_instructions', 10, 2 );`

Unless this line is placed directly next to it in the plugin - which is clearly not a good fix..

**Comment by acf-extended** [comment]
Hello,

Sorry for the late answer, I'm quite busy working on ACF Extended latety. I just tested to add a local field group using the `acf/init` hook, on a blank WP + ACF Pro + ACF Extended install, and everything works as expected (with WYSIWYG fields on both local and DB field groups). You probably have something specific in your field groups that leads to compatibility problems.

The `add_filter('acf/pre_render_fields', 'acfe_fields_wrapper_instructions', 10, 2)` part of the ACF Extended code is quite old TBH, and deserve to be enhanced. Please try to apply the following fix, maybe that will fix your issue.

In the file: `/acf-extended/includes/fields-settings/fields.php`, replace both filters:
* `add_filter('acf/pre_render_fields', 'acfe_fields_wrapper_instructions', 10, 2)`
* `add_filter('acf/field_wrapper_attributes', 'acfe_fields_wrapper', 10, 2)`

With the following code:

```php
add_filter('acf/pre_render_fields', 'acfe_fields_wrapper_instructions', 10, 2);
function acfe_fields_wrapper_instructions($fields, $post_id){
    
    acf_disable_filter('acfe/instructions_tooltip');
    
    if(!isset($fields[0]))
    	return $fields;
    
    $field = $fields[0];
    
    if(!acf_maybe_get($field, 'parent'))
        return $fields;
    
    $field_group = acf_get_field_group($field['parent']);
    
    if(!$field_group)
        return $fields;
    
    if(acf_maybe_get($field_group, 'instruction_placement') !== 'acfe_instructions_tooltip')
    	return $fields;
    
    acf_enable_filter('acfe/instructions_tooltip');
    
    return $fields;
    
}

add_filter('acf/field_wrapper_attributes', 'acfe_fields_wrapper', 10, 2);
function acfe_fields_wrapper($wrapper, $field){
    
    if(!acf_maybe_get($field, 'label')){
    
        $wrapper['class'] .= ' acfe-no-label';
    
    }
    
    if(acf_is_filter_enabled('acfe/instructions_tooltip') && acf_maybe_get($field, 'instructions')){
        
        $wrapper['data-acfe-instructions-tooltip'] = acf_esc_html($field['instructions']);
        
    }
    
    return $wrapper;
    
}
```

I'll add the code enhancement in the next update.

Regards.

**Comment by qstudio** [comment]
Thanks for the proposed fix, but I'm sorry to say that we removed the plugin and worked directly with filters and options within ACF - as we needed a solution quickly.

**Comment by acf-extended** [comment]
Hello,

No problem. The code will be included in the next patch anyway, since it's clearly better way to achieve the tooltip instructions placement. If you ever retry to activate the plugin on the said website, feel free to let me know if that fixed your issue.

Have a nice day!

Regards.
