### ISSUE TITLE
Empty error message for import without file

### ISSUE THREAD

**Issue by rtpHarry** [acf-extended/ACF-Extended#61]
**Describe the bug**
If you click import on one of the import buttons, without setting the file, the error message the appears is just a `.`:

![image](https://user-images.githubusercontent.com/1038062/95062311-b4cc3200-06f4-11eb-8f7e-06b23b0b9512.png)

**To Reproduce**
Go to import and click import without selecting a file first.

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback! That will be fixed in the patch.

Regards.

**Comment by acf-extended** [comment]
Hello,

Just a heads up to let you know that the latest ACF Extended 0.8.7.5 Update fix this issue!

Sorry for the inconvenience.

Have a nice day!

Regards.
