### ISSUE TITLE
[0.8.7.6] Clone values are empty after a form is rendered in a page

### ISSUE THREAD

**Issue by damien-pilot-in** [acf-extended/ACF-Extended#66]
**Describe the bug**
Clone fields returns no value after an ACFE form is rendered.

**To Reproduce**
- Render an ACFE Form in a page.
- Add some code after the rendering of the form calling a clone field.
- Calling the field returns no value.

**Expected behavior**
Clone values should be returned.

**Screenshots**  _(contains issue & fix)_
File is `/includes/modules/form/admin.php L400`

![Issue & Fix inside](https://user-images.githubusercontent.com/62112531/103273474-ae7de700-49bf-11eb-88cf-4c38366f2d8d.png)

**Fix**
```php
$field_group['fields'] = acf_get_fields($field_group);

// Add this
acf_enable_filter('clone');
```

**WordPress & ACF**
WordPress version: Latest
ACF Pro version: Latest
ACFE Version: 0.8.7.6

**Comment by acf-extended** [comment]
Hello @damien-pilot-in :)

Thanks for this very details reported! This issue will be fixed in the next patch.

Sorry for the inconvenience.

Regards.

**Comment by acf-extended** [comment]
Hello,

Just a heads up to let you that the latest 0.8.8 Update fixed this issue.

Have a nice day!

Regards.
