### ISSUE TITLE
Broken overlay when using the Edition Modal feature for an ACF on a Widget.

### ISSUE THREAD

**Issue by vinny-smooches** [acf-extended/ACF-Extended#70]
**Describe the bug**
When creating a field group for a widget using ACF, in conjunction with the edition modal feature the modal pop up is below certain areas of the "widgets" admin page, this includes the modal overlay itself. Making it impossible to use the modal to edit field content. 

**To Reproduce**
Add an ACF field group to a widget with a field inside of it, use the ACF rules, and pick a widget to add the fields too. Make the field group use the "Edition Modal" option. When editing the widget, on the widget admin page, and clicking the edit button for the field group, the modal will open, but the modal content will be below some of the page content including the modal overlay (see screenshot)

**Expected behavior**
Modal should open normally and above all other elements on the page. Modal should also allow users to edit the fields.

**Screenshots**
![Screen Shot 2021-02-01 at 2 58 28 PM](https://user-images.githubusercontent.com/38591364/106517881-b3422900-649e-11eb-95b8-3fa7ddd9d00b.png)

**WordPress & ACF**
WordPress version: 5.6
ACF Pro version: 5.9.4
ACF add-ons: Advanced Custom Fields: Extended

This normally works everywhere else I have ever used this feature, it has become one of the most used aspects of my CMS builds. I think widgets are a bit of an outmoded thing and perhaps this feature was not really tested in this exact use-case. In my most recent project, it has become necessary for using the "edition modal" feature for editing fields on a widget.

**Comment by acf-extended** [comment]
Hello!

Thanks for the detailed report! You're right, "Edit in modal" should work in widgets. It's probably just a CSS `z-index` problem. Widget is kinda outdated, that's probably why I haven't tested this feature extensively here, and probably also why nobody reported it before :)

I'm adding it to the todo list for the next patch.

Once I figure it out, I'll update you here to send you a quick fix if you don't want to wait for the patch.

Have a nice day!

Regards.

**Comment by acf-extended** [comment]
Hello,

Just a heads up to let you that the latest 0.8.8 Update fixed this issue.

Have a nice day!

Regards.
