### ISSUE TITLE
Feature request single meta and delete orphan meta data

### ISSUE THREAD

**Issue by wpsumo** [acf-extended/ACF-Extended#71]
**Is your feature request related to a problem? Please describe.**
That single meta, delete orphan is on per post basis.

**Describe the solution you'd like**
Possibility to delete orphan meta data in bulk and option save single meta and revert to acf native in bulk.

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback! I have plans for such script and UI. It will come in a near future. Stay tuned!

I'm closing the ticket here.

Regards.

**Comment by wpsumo** [comment]
Many thanks, would be great! Would save to single meta enable and disable be available in bulk/ one simple setting as well?

**Comment by acf-extended** [comment]
Hello,

Scripts UI will allow you to write your own scripts and run them from the admin. So you'll be able to do anything you want to.

More info will be available when the feature will be out.

Regards.

**Comment by wpsumo** [comment]
Okay so there will not be a solution provided by ACFE to run and delete orphan meta data. It will only be UI to run custom scripts to begin with at least? +1 for ACFE quality approved to delete orphan meta from posts and options pages 👍

**Comment by acf-extended** [comment]
Hello,

The feature is not done yet. More info will be available when it will be out.

Regards.
