### ISSUE TITLE
Add advanced form

### ISSUE THREAD

**Issue by sebastienserre** [acf-extended/ACF-Extended#74]
Hello,

Today, ACF Extended is making what ACF make natively but in an easy way. Without coding, you can create a front end form with Field group and that's great.

I think, you can add a "plus" by adding more feature. The one I think is, when we chose to create a post on form submit, ACF Extended should ask if the user want to fill the native WordPress fields too.

Today, If I use ACF and ACF Form to create a post from Front, I will need to create a text field for the title and a WYSIWYG for the content for example.
These both fields will be show on Front and in settings, I'll be able to map them to WordPress title and WordPress content. OK

But in Back Office, I will have 2 title fields (The native and the ACF one), the same for Content. What if in Back office I (as an admin) update the native title or content and allow the users to update the post in Front ?

I think, ACF extended, when the user chose to save the front as a post should add fields on front only to save native WordPress data.

I've spoken of title and content, but I think the same for all native data post (Taxonomy for example) to avoid double info.

**Comment by acf-extended** [comment]
Hello,

The current ACFE Form logic allow the developers to use any ACF field to save WordPress data (Title, Content, etc...) and not save it as meta data. So there is no really duplicate data here.

However, the developer has to hide those fields from the admin UI using the [Advanced Settings](https://www.acf-extended.com/features/field-settings/field-advanced-settings) feature, [Field Visibility](https://www.acf-extended.com/features/field-settings/field-visibility) settings or simply `acf/prepare_field`.

This logic can seems a bit weird at first, but it's the only solution which allow full control of every single field render and their position in the form render (some developers may want to use "Textarea" as post title, and put it at the end of the form).

Additional settings like "Custom HTML Render" in the ACFE Form UI also allow to fine tune this logic.

Hope it helps!

Regards.
