### ISSUE TITLE
Post Statuses Not Working

### ISSUE THREAD

**Issue by lindabenefield** [acf-extended/ACF-Extended#77]
**Describe the bug**
I looked on your website and all it says is that you CAN make a field for post statuses, but there is not one place that tells us HOW. I have tried so many things, but nothing is working. 

**To Reproduce**
1. Add new field group
2. add post statuses field 
3. radio field, or select field, or checkbox field

**Expected behavior**
When a user creates or edits a Notebook post, they can select the status they want, but nothing changes. The post is still public. I don't see a place to set it as any type of field. 

**Screenshots**

**WordPress & ACF**
WordPress version: 5.7.1
ACF Pro version: 5.9.5
ACF add-ons: ACF Frontend Pro, ACF Extended, Dynoments Rexy, JetEngine, Elementor PRO

I really really need to get this to work so users can set their own posts to private or public once the site launches. Thanks.

**Comment by lindabenefield** [comment]
Nevermind. I deleted and reinstalled the plugin and now I finally have the choices of a checkbox, select, or radio field so I don't have to try to do it myself.

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback! The [Post Statuses field type](https://www.acf-extended.com/features/fields/post-statuses) doesn't require you to set values/labels. You just have to select it from the dropdown, and it will automatically show all registered post statuses of WordPress (you can allow only specific ones if you want tho). See screenshot: https://i.imgur.com/1SEgBKI.png

Please note that this field was made for developers and will not update the current post to the selected post status. It simply allows the developer to display post statuses, let the user save it as a meta and then do what he wants with it, just like the Post Types field, Taxonomes field, User Roles field etc...

It you want to update the current post status based on that field value, you'll have to rely on the `acf/update_value` hook, and write your own script. As a side note, the [Post Field](https://www.acf-extended.com/features/fields/post-field) allows you to move the native WordPress status selector to a field group. This field will receive more updates in the future allowing even more customization.

Hope it helps!

Regards.
