### ISSUE TITLE
2 revisions are created

### ISSUE THREAD

**Issue by yangkennyk** [acf-extended/ACF-Extended#8]
**Describe the bug**
When ACFE is enabled. A CPT with revisions support will create two revisions. The first revision shows all ACF fields being deleted. The second revision shows them all being added again.

**To Reproduce**
Have a CPT that supports revisions. Save the post. 2 revisions are created

**Expected behavior**
There should only be 1 revision created showing the change. 

**Screenshots**

**WordPress & ACF**
WordPress version: 5.3
ACF Pro version: 5.8.7

**Comment by acf-extended** [comment]
Hello Yang,

Yes this bug has been reported earlier this week, and it will be fixed in the next 0.8.3 patch (very soon!). Thanks for the report!

Regards.

**Comment by acf-extended** [comment]
Hello yangkennyk ,

Just to let you know that the latest ACF Extended 0.8.3 Update fixed this issue.

Thanks for the report! :)

Regards.
