### ISSUE TITLE
Validation does not work along ACF and Gutenburg blocks

### ISSUE THREAD

**Issue by poyeshsoftware** [acf-extended/ACF-Extended#80]
**Describe the bug**
Hi Guys, we have ACF extended pro in our company, we are using it to make Gutenberg blocks for our custom component site builder, but I noticed that the ACF validation does not work within Gutenberg blocks. 
for example min and max... anything, and we need to put some validations in there, do you have any solutions or how we can solve this problem

Thanks

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback!

The ACF field validation doesn't work with Gutenberg, this is a known issue and a feature that should be released in a future update. You will find more information on this [ACF Githbub issue](https://github.com/AdvancedCustomFields/acf/issues/113). It is also listed in the official [ACF known issues](https://www.advancedcustomfields.com/resources/known-issues/).

Unfortunately the min/max setting from ACF Extended Pro rely on that native ACF validation API, so it won't work until ACF release a fully working patch.

As a side note, if you have another support question regarding ACF Extended Pro, I invite you to use the ticket system in your [ACF Extended Website account](https://www.acf-extended.com/account), as I cannot really provide support for PRO features here on Github.

Hope it helps!

Have a nice day!

Regards.
