### ISSUE TITLE
Flexible content Default Layouts State bug

### ISSUE THREAD

**Issue by sh-sabbir** [acf-extended/ACF-Extended#84]
### Describe the bug
Default Layouts State is not working as expected. 

**Current Behavior**
Collapsed == Opened
Opened == Collapsed
Always opened == Collapsed

**To Reproduce**
Just create a flexible content field and some layout. Also add Dynamic render and Dynamic preview.
Now create a page and add layouts. You will see layouts default state is open if you select collapsed as default state. If you set anything else layout will be collapsed by default

**Expected behavior**
Collapsed == Collapsed
Opened == Opened
Always opened == Opened

**Screenshots**
https://prnt.sc/1srxzkq

**WordPress & ACF**
WordPress version: 5.8.1
ACF Pro version: 5.10.2
ACF add-ons: N/A

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback!

I just tested it, and the feature works fine on my end. Video of the test: https://i.imgur.com/izipJxW.mp4

Note that "Collapsed" means that the preview is displayed on page load, and "Opened" means the layout's sub fields are displayed on page load.

Do you get the same result?

Regards.
