### ISSUE TITLE
menu_order isn't respected when acfe enabled

### ISSUE THREAD

**Issue by yangkennyk** [acf-extended/ACF-Extended#9]
**Describe the bug**
the "menu_order" isn't respected when acfe is enabled. 

**To Reproduce**
enable plugin and menu_order no longer works

**Expected behavior**
menu_order should work

**Screenshots**

**WordPress & ACF**
WordPress version: 5.3
ACF Pro version: 5.8.7

**Comment by acf-extended** [comment]
Hello,

May I ask you some more informations please? Which `menu_order` are you referring to?

**Comment by acf-extended** [comment]
Hello,

Any news about this issue?

Regards.

**Comment by acf-extended** [comment]
Hello,

I'm closing the ticket now, as there's still no news about it. If someone has a similar problem, feel free to re-open the ticket.
