### ISSUE TITLE
Modal Overlay and card overlap

### ISSUE THREAD

**Issue by kent09** [acf-extended/ACF-Extended#95]
**Describe the bug**
When editing the Flexible Content the modal overlay overlape in the modal and also the other card 
**To Reproduce**
create flexible content with multiple content and the content set to block layout

**Expected behavior**
the modal should showing first not under in both card and overlay

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/6016706/144432548-a772d3f4-e3f4-47e1-b370-377969005932.png)

**WordPress & ACF**
WordPress version: 5.8.2
ACF Pro version: 5.11.3
Advanced Custom Fields: Extended version: 0.8.8.6

ACF add-ons:
Advanced Custom Fields: Table Field

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback!

I just tested it and it works fine here. Here is the video of my test: [https://i.imgur.com/ogJtAlg.mp4](https://i.imgur.com/ogJtAlg.mp4)

Maybe you have some CSS conflict with a custom theme or plugin? I would recommend to disable your plugins one by one and try to switch to the native WP Twenty Twenty One theme, until you found the cause of the issue.

Hope it helps!

Have a nice day!

Regards.

**Comment by acf-extended** [comment]
Hello @kent09,

I've seen that you closed the ticket, which means you probably found the cause of the issue?

Can you please describe what causing it? It might help an another user in a similar situation in the future.

Thanks in advance.

Have nice day!

Regards.

**Comment by kent09** [comment]
Hello,

yes you are right in "Maybe you have some CSS conflict with a custom theme or plugin?" it is custom theme issue that causing it to work that way. 

thank you for the respond anyway :)

Regards.

**Comment by acf-extended** [comment]
Hello,

Okay cool. Thanks :)

Regards.
