### ISSUE TITLE
Required code editor field causes error even if not empty

### ISSUE THREAD

**Issue by xxvii** [acf-extended/ACF-Extended#98]
**Describe the bug**
When there are more than one code editor fields and they are all required, the first one causes an error on page save, even if it contains a value

**To Reproduce**
Create a field group and assign it to pages
Add two (or more) code editor fields and set them as required
Create a page, write something inside both the code editor fields
Save the page
The first code editor field causes an error

**Expected behavior**
The page should be saved without errors, as all required fields contain a value

**WordPress & ACF**
WordPress version: 5.8.3
ACF Pro version: 5.11.4
ACF Extended: 0.8.8.7

**Comment by acf-extended** [comment]
Hello,

Thanks for the feedback, and sorry for the late answer.

I didn't manage to reproduce the issue, both on Classic Editor or Gutenberg editor, on a blank WP install (with ACF & ACF Extended only).

If yo ustill have this issue I would recommend to setup a clean WP install with ACF Pro + ACF Extended only, and test the feature on it. If you prefer to keep your installation, then try to disable all your plugins one-by-one (at the exception of ACF Pro & ACF Extended) until you find which one cause the issue.

If the problem persists, I would suggest switch to the native WP Twenty Twenty Two theme, to make sure you don’t have any custom code in your theme that would break the feature.

Hope it helps!

Have a nice day!

Regards.
