### ISSUE TITLE
Save block type in json automatically for version control.

### ISSUE THREAD

**Issue by razvanFrandes** [acf-extended/ACF-Extended#99]
Hello,

I find block types very easy to use and saves a lot of time, although I wish there is something to save the block types in a json format and be able to sync between environments and load from there. I know this feature is pretty new in ACF.

Filed groups has this filter acf/settings/save_json where you can select the path where you want to save/load the fields.
Hope it will be in the new version.

Thank you :)

**Comment by eIiot** [comment]
+1

**Comment by acf-extended** [comment]
Hello,

Just a heads up to let you know that the latest ACF Extended Pro 0.8.9 update introduced the PHP/Json sync for Block Types, Options Pages, Post Types, Taxonomies & Templates.

Have a nice day!

Regards.
